name: Deploy to EC2/Kubernetes

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build Deep's Portfolio website
        run: npm run build

  deploy:
    name: Deploy to EC2 K8 on master branch push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to EC2 on Kubernetes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo yum update -y
            sudo yum install -y nodejs
            cd /home/ec2-user/
            sudo mv * .
            npm run build
            npm run dev