name: Deploy to EC2/Kubernetes

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build Deep's Portfolio website
        run: npm run build

  deploy:
    name: Deploy to EC2 K8 on master branch push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Server 1
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ec2-user/portfolio/
          remote_host: "${{ secrets.EC2_HOST }}"
          remote_user: "${{ secrets.EC2_USERNAME }}"
          remote_key: "${{ secrets.EC2_SSH_KEY }}"
      
      - name: Deploy to EC2 on Kubernetes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/portfolio/
            sudo yum update -y
            sudo yum install -y nodejs
            npm run build
            npm run dev